name: .NET

permissions:
  actions: read
  contents: read
  security-events: write

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: csharp

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore ll.sln

    - name: Build solution
      run: dotnet build ll.sln --no-restore --configuration Release

    - name: Run tests (optional, skip if not needed)
      run: dotnet test ll.sln --no-build --verbosity normal

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2

