# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
# This workflow will build a .NET project and scan it for vulnerabilities using CodeQL

name: .NET

permissions:
  actions: read
  contents: read
  security-events: write

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: csharp

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore ll.sln

    - name: Build
      run: dotnet build ll.sln --no-restore

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
