name: .NET
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Check Backend project existence
      id: check_files
      uses: andstor/file-existence-action@v2
      with:
        files: "Backend/BankingApp/BankingApp.csproj"
    - name: Restore dependencies
      if: steps.check_files.outputs.files_exists == 'true'
      run: dotnet restore Backend/BankingApp/BankingApp.csproj
    - name: Build
      if: steps.check_files.outputs.files_exists == 'true'
      run: dotnet build Backend/BankingApp/BankingApp.csproj --no-restore
